services:
  # Backend service
  - type: web
    name: food-delivery-backend
    env: node
    nodeVersion: 22.x
    plan: free
    rootDir: Backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: web
    name: food-delivery-frontend
    env: static
    nodeVersion: 22.x
    plan: free
    rootDir: Frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://fastship-order-nl-zkxw.onrender.com

  # Admin service  
  - type: web
    name: food-delivery-admin
    env: static
    nodeVersion: 22.x
    plan: free
    rootDir: Admin
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://fastship-order-nl-zkxw.onrender.com
